apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-manager
  template:
    metadata:
      labels:
        app: key-manager
        key-manager: true
    spec:
      containers:
      - name: key-manager
        date: {{ .Release.Time.Seconds | quote }}
        image: key-manager:latest
        imagePullPolicy: Never
        env:
        - name: ETCD_USER
          value: {{ .Values.etcd_user | quote }}
        - name: ETCD_PASSWORD
          value: {{ .Values.etcd_password | quote }}
        - name: ETCD_CLUSTER_URI
          value: {{ .Values.etcd_cluster_uri | quote }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: key-manager
spec:
  selector:
    app: key-manager
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
